name: Publish

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git init .
          git remote add origin "https://github.com/${GITHUB_REPOSITORY}.git"
          git fetch --depth=1 origin "${CHECKOUT_REF}"
          git checkout --detach FETCH_HEAD
        env:
          CHECKOUT_REF: ${{ inputs.ref || github.ref }}

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - run: npm install
      - run: npm test
      - run: npm run pack:dry
      - run: npm publish
